version: "3.9"
services:
  postgres_db:
    image: docker.io/bitnami/postgresql:latest
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres_db
    image: smart_learn:v1
    env_file:
      - .env 
    ports:
      - "8080:8080"
    command: sh -c "chmod +x /api/build.sh && sh /api/build.sh && /api/entrypoint.sh"
    restart: always

volumes:
  postgres_data: