name: Django CI - Test Phase

on:
  push:
    branches: [ "feature/deployment" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DJANGO_SUPERUSER_EMAIL: hello@smartlearn.com
      SECRET_KEY: ${{ vars.DJANGO_SECRET_KEY }}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root@pass1
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres_db:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          # POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
   
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Run Unit Tests
    - name: Run Tests
      run: |
        python manage.py test
      continue-on-error: true # continue even if tests fail
    
    # Run Security Scan with Bandit
    - name: Install and Run Security Scan
      run: |
        pip install git+https://github.com/PyCQA/bandit#egg=bandit
        ./pipeline-scripts/bandit.sh
      continue-on-error: true

    - name: Run ZAP Scan
      run: |
        docker run -t owasp/zap2docker-weekly zap-api-scan.py -t https://www.example.com/openapi.json -f openapi