name: Django CI - Test Phase

on:
  push:
    branches: [ "feature/deployment" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DJANGO_SUPERUSER_EMAIL: hello@taskmaster.com
      SECRET_KEY: "someSampleKeydyNBYa83J+2RpTstv36ZSqX48D2EKBfz+OplD22GPNXoo/POvAwZI6BwUPKB54FSwiszzOfquIIFiJPfmniCA"
      POSTGRESQL_DATABASE: dockerdc
      POSTGRESQL_PASSWORD: mysecret1@Passwd
      POSTGRESQL_USERNAME: myuser
      POSTGRESQL_HOST: postgres_db
      POSTGRESQL_PORT: 5432
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres_db:
        image: docker.io/bitnami/postgresql:latest
        env:
          POSTGRESQL_DATABASE: ${{ env.POSTGRESQL_DATABASE }}
          POSTGRESQL_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
          POSTGRESQL_USERNAME: ${{ env.POSTGRESQL_USERNAME }}
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test